#!/usr/bin/env python3
"""Generate a C file embedding the ADAM system ROMs into the binaries.

Usage: embed-roms.py <out.c> <OS7.rom> <EOS.rom> <WP.rom>

The ROM images are Coleco-copyrighted and are NOT committed to this
repository (tools/adamcore/roms is git-ignored); drop your own copies there
before building. The generated C file lives in the build tree only.
"""

import sys

EXPECTED = {"os7": 0x2000, "eos": 0x2000, "wp": 0x8000}


def emit(out, name, data):
    out.write(f"const uint8_t adam_rom_{name}[{len(data)}] = {{\n")
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        out.write(f"    {row},\n")
    out.write("};\n\n")


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    out_path, os7_path, eos_path, wp_path = sys.argv[1:5]
    roms = {}
    for name, path in (("os7", os7_path), ("eos", eos_path), ("wp", wp_path)):
        try:
            with open(path, "rb") as f:
                data = f.read()
        except OSError as e:
            sys.exit(
                f"embed-roms: cannot read {path}: {e}\n"
                "Place EOS.rom, OS7.rom and WP.rom in tools/adamcore/roms/."
            )
        if len(data) != EXPECTED[name]:
            sys.exit(
                f"embed-roms: {path} is {len(data)} bytes, "
                f"expected {EXPECTED[name]}"
            )
        roms[name] = data

    with open(out_path, "w") as out:
        out.write("/* Generated by tools/adamcore/embed-roms.py -- do not edit.\n")
        out.write(" * ADAM system ROM images embedded for a self-contained app.\n")
        out.write(" */\n\n#include <stdint.h>\n\n")
        for name in ("os7", "eos", "wp"):
            emit(out, name, roms[name])


if __name__ == "__main__":
    main()
